
config:
	kubectl apply -f configmap.yaml

start-naver:
	helm install naver naver

start-daum:
	helm install daum daum

start-nate:
	helm install nate nate

start-naver-terms:
	helm install naver-terms naver-terms

stop-naver:
	helm uninstall naver

stop-daum:
	helm uninstall daum

stop-nate:
	helm uninstall nate

stop-naver-terms:
	helm install naver-terms

