###

GET {{host}}/_cluster/settings
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

###

GET {{host}}/_cluster/allocation/explain?pretty
Authorization: Basic {{username}} {{password}}
Content-Type: application/text
Accept: application/text

###

POST {{host}}/_cluster/reroute
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

###

GET {{host}}/_cluster/allocation/explain?pretty
Authorization: Basic {{username}} {{password}}
Content-Type: application/text
Accept: application/text

###
# 재시작 : https://www.elastic.co/guide/en/elasticsearch/reference/current/restart-upgrade.html
# 1. Disable shard allocation.
PUT {{host}}/_cluster/settings
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

{
  "persistent": {
    "cluster.routing.allocation.enable": "all"
  }
}

###

PUT {{host}}/_cluster/settings
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

{
  "transient": {
    "cluster.routing.rebalance.enable": "all",
    "cluster.routing.allocation.enable": "all",
    "cluster.routing.allocation.allow_rebalance": "always",
    "cluster.routing.allocation.node_concurrent_recoveries": 3
  }
}

### shut down 절차

PUT {{host}}/_cluster/settings
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

{
  "persistent": {
    "cluster.routing.allocation.enable": "none"
  }
}

###

PUT {{host}}/_cluster/settings
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

{
  "persistent": {
    "cluster.routing.allocation.enable": "all"
  }
}

###

GET {{host}}/_cluster/state?pretty
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

###

GET {{host}}/_cluster/health?wait_for_status=yellow&timeout=50s
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

###

PUT {{host}}/_cluster/settings
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

{
  "persistent": {
    "indices.breaker.request.limit" : "45%"
  }
}

###
