

###

POST {{host}}/_flush
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

###

DELETE {{host}}/corpus-wiki-th
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

###
