###

GET {{host}}
Authorization: Basic {{username}} {{password}}
Accept: application/text

###

POST {{host}}/_flush/synced
Authorization: Basic {{username}} {{password}}
Accept: application/text

###

POST {{host}}/corpus-baseball-game-log-2015/_flush/synced
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

###

GET {{host}}/_stats?filter_path=**.commit&level=shards
Authorization: Basic {{username}} {{password}}
Accept: application/text

###

GET {{host}}/_tasks?detailed=true&actions=*reindex
Authorization: Basic {{username}} {{password}}
Content-Type: application/text
Accept: application/text

###

GET {{host}}/_tasks?detailed=true
Authorization: Basic {{username}} {{password}}
Content-Type: application/text
Accept: application/text

###

POST {{host}}/_flush/synced
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

###

GET {{host}}/_nodes/settings?pretty
Authorization: Basic {{username}} {{password}}
Content-Type: application/text
Accept: application/text

###

GET {{host}}/_nodes?pretty
Authorization: Basic {{username}} {{password}}
Content-Type: application/text
Accept: application/text

###
