###

GET {{host}}/log_gamechatglobal_*/_search
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

###

GET {{host}}/log_gamechat_cache/_search
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

###

GET {{host}}/log_gamechat_global2_2*/_search
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

{
  "query": {
    "bool": {
      "filter": {
        "match": {
          "gameServer": "7"
        }
      }
    }
  }
}

###

GET {{host}}/log_gamechat_global2_2*/_search
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

{
  "size": 0,
  "aggregations": {
    "min_date": {
      "min": {
        "field": "localDateTime"
      }
    },
    "max_date": {
      "max": {
        "field": "localDateTime"
      }
    }
  },
  "query": {
    "bool": {
      "filter": {
        "match": {
          "gameServer": "7"
        }
      }
    }
  }
}

###

GET {{host}}/log_gamechat_cache/_search
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

###

GET {{host}}/log_gamechat_cache/_doc/date_range
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

###

GET {{host}}/log_gamechat_cache/_doc/server_info
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

###

DELETE {{host}}/log_gamechat_cache/_doc/room_list
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

###

GET {{host}}/log_gamechat_cache/_doc/date_range.l2-tw
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

###

GET {{host}}/log_gamechat_cache/_doc/server_info
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

###

GET {{host}}/log_gamechat_cache/_doc/date_range.l2-en
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

###

POST {{host}}/log_gamechat_cache/_doc/date_range.l2-en
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

< mchat/date_range.l2-en.json

###

POST {{host}}/log_gamechat_cache/_doc/date_range.l2-tw
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

< mchat/date_range.l2-tw.json

###

POST {{host}}/log_gamechat_cache/_doc/room_list.l2-en
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

< mchat/room_list.l2-en.json

###

POST {{host}}/log_gamechat_cache/_doc/room_list.l2-tw
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

< mchat/room_list.l2-tw.json

###

POST {{host}}/log_gamechat_cache/_doc/room_list.l2m-ko
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

< mchat/room_list.l2m-ko.json

###

POST {{host}}/log_gamechat_cache/_doc/server_info
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

< mchat/server_info.json

###

GET {{host}}/log_gamechat_cache/_doc/room_list
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

###

GET {{host}}/log_gamechat_cache/_search
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

###

GET {{host}}/log_gamechat_test_kr*/_search?size=50
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

{
  "query": {
    "function_score": {
      "query": {
        "match": {
          "uchar_msg": {
            "query": "몰라양아치생키들이"
          }
        }
      }
    }
  }
}

###
