###

PUT {{host}}/_ingest/pipeline/text_char_pipeline
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

{
  "processors": [
    {
      "character_kr": {
        "field": "text",
        "columns": [
          "uchar_text",
          "ujaso_text",
          "ucho_text"
        ],
        "preprocess_stages": [
          "sym_to_kor",
          "sym_to_space"
        ]
      }
    }
  ]
}

###

GET {{host}}/_ingest/pipeline/character_kr
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

###

GET {{host}}/{{index}}/_search
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

###

GET {{host}}/{{index}}/_doc/1?pipeline=character_kr_test
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

{
  "msg": "“지난해 금융권 펀드 투자자보호 수준 악화”"
}

###

GET {{host}}/{{index}}/_termvectors/1?fields=ujaso_msg
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

###

PUT {{host}}/{{index}}
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

{
  "settings": {
    "index": {
      "default_pipeline": "text_char_pipeline",
      "max_ngram_diff": 10,
      "mapping.total_fields.limit": 5000
    },
    "analysis": {
      "analyzer": {
        "ngram_analyzer": {
          "tokenizer": "ngram_tokenizer"
        },
        "space_analyzer": {
          "tokenizer": "space_tokenizer"
        }
      },
      "tokenizer": {
        "ngram_tokenizer": {
          "type": "ngram",
          "min_gram": 1,
          "max_gram": 9,
          "token_chars": [
            "letter",
            "digit"
          ]
        },
        "space_tokenizer": {
          "type": "whitespace",
          "max_token_length": 4096
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "date": {
        "type": "date"
      },
      "document_id": {
        "type": "text"
      },
      "source": {
        "type": "text"
      },
      "text": {
        "type": "text",
        "analyzer": "ngram_analyzer"
      },
      "keywords": {
        "type": "text",
        "analyzer": "space_analyzer"
      }
    }
  }
}

###

GET {{host}}/{{index}}/_search
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

###

GET {{host}}/{{index}}/_doc/bbs-comment-1251679-2429087?pipeline=character_kr
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

###
