###

POST {{host}}/_reindex?wait_for_completion=false
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

{
  "source": {
    "index": "crawler-facebook-en-new"
  },
  "dest": {
    "index": "crawler-facebook-en"
  }
}

###

DELETE {{host}}/crawler-dictionary-example-youdao
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

###

POST {{host}}/_reindex?wait_for_completion=false
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

{
  "source": {
    "remote": {
      "host": "https://corpus.ncsoft.com:9200",
      "username": "elastic",
      "password": "nlplab"
    },
    "index": "crawler-jisikman-2018"
  },
  "dest": {
    "index": "crawler-jisikman-2018"
  }
}

###




###



###



###
