###

POST {{host}}/_reindex?wait_for_completion=false
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

{
  "source": {
    "index": "crawler-dictionary-example-youdao"
  },
  "dest": {
    "index": "crawler-dictionary-example-youdao-zhen"
  }
}

###

DELETE {{host}}/crawler-dictionary-example-youdao
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

###
