###

GET {{host}}/crawler-naver-economy-*/_search
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "category": ","
          }
        }
      ]
    }
  }
}

###

GET {{host}}/crawler-naver-economy-2020/_search
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

{
  "track_total_hits": true,
  "query": {
    "bool": {
      "must_not": {
        "exists": {
          "field": "content"
        }
      }
    }
  }
}

###
