###

GET {{host}}/_tasks?detailed=true&actions=*reindex
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

###

GET {{host}}/_tasks/QLnqKErAQxuOteVoPZAtBg:78344755
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

###
