
###

GET http://yonhap01:30006/_cat/indices?v&s=index&h=index,docs.count,store.size,tm
Content-Type: application/json
Accept: application/text

###

GET http://yonhap01:30006/log_mtdemo_*/_search
Content-Type: application/json
Accept: application/text

###

GET http://yonhap01:30006/log_mtdemo_*/_search
Content-Type: application/json
Accept: application/text

{
  "from": 0,
  "size": 20,
  "track_total_hits": true,
  "query": {
    "bool": {
      "filter": [
        {
          "match": {
            "client_info.game_code": "l2-en"
          }
        },
        {
          "match": {
            "source_lang": "en"
          }
        },
        {
          "match": {
            "target_lang": "tw"
          }
        }
      ],
      "must": {
        "range": {
          "client_info.request_date": {
            "gte": "2020-01-01",
            "lte": "2020-05-20",
            "format": "yyyy-MM-dd"
          }
        }
      }
    }
  }
}

###

GET http://yonhap01:30006/log_mtdemo_*/_mapping
Content-Type: application/json
Accept: application/text

###
