###

POST {{host}}/{{index}}/_delete_by_query
Content-Type: application/json
Accept: application/json

{
  "query": {
    "bool": {
      "must": {
        "match": {
          "entry": "cartoon"
        }
      }
    }
  }
}

###

POST {{host}}/{{index}}/_delete_by_query
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

{
  "track_total_hits": true,
  "_source": [
  ],
  "query": {
    "bool": {
      "must_not": [
        {
          "exists": {
            "field": "entry"
          }
        }
      ]
    }
  }
}

### 특정 시간 이후의 컬럼을 변경한다.

POST {{host}}/{{index}}/_update_by_query
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

{
  "query": {
    "bool": {
      "must": {
        "range": {
          "date": {
            "gte": "2020-05-27T14:50:00+09:00"
          }
        }
      }
    }
  },
  "script": {
    "source": "ctx._source['state'] = ''"
  }
}

###

POST {{host}}/{{index}}/_update_by_query
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

{
  "query": {
    "match_all": {}
  },
  "script": {
    "source": "ctx._source['state'] = ''"
  }
}

###

POST {{host}}/{{index}}/_update_by_query
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

{
  "query": {
    "match_all": {}
  },
  "script": {
    "source": "ctx._source.remove('link')"
  }
}

###
