# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

###
GET http://gollum:9200/_cluster/settings
Content-Type: application/json
Accept: application/text


###
GET http://gollum:9200/_cluster/allocation/explain?pretty
Content-Type: application/text
Accept: application/text


###
POST http://gollum:9200/_cluster/reroute
Content-Type: application/json
Accept: application/json


###
GET http://gollum:9200/_cluster/allocation/explain?pretty
Content-Type: application/text
Accept: application/text


###
# 재시작 : https://www.elastic.co/guide/en/elasticsearch/reference/current/restart-upgrade.html
# 1. Disable shard allocation.
PUT http://gollum:9200/_cluster/settings
Content-Type: application/json
Accept: application/text

{
  "persistent": {
    "cluster.routing.allocation.enable": "all"
  }
}


###
PUT http://gollum:9200/_cluster/settings
Content-Type: application/json
Accept: application/text

{
  "transient": {
    "cluster.routing.allocation.enable": "all",
    "cluster.routing.allocation.node_concurrent_recoveries": 3,
    "cluster.routing.allocation.allow_rebalance": "always",
    "cluster.routing.rebalance.enable": "all"
  }
}


###
# shut down 절차
PUT http://gollum:9200/_cluster/settings
Content-Type: application/json
Accept: application/text

{
  "persistent": {
    "cluster.routing.allocation.enable": "none"
  }
}


###
PUT http://gollum:9200/_cluster/settings
Content-Type: application/json
Accept: application/text

{
  "persistent": {
    "cluster.routing.allocation.enable": "all"
  }
}



###
GET http://gollum:9200/_cluster/state?pretty
Content-Type: application/json
Accept: application/text

###

