# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

###

DELETE {{host}}/.monitoring-*
Content-Type: application/json
Accept: application/json

###

GET {{host}}/_cat/indices?v&s=index&h=index,docs.count,store.size,tm
Content-Type: application/json
Accept: application/text

###

GET {{host}}/crawler-news-mk-2019/_search
Content-Type: application/json
Accept: application/json

{
  "track_total_hits": true,
  "_source": [
    "title",
    "url"
  ],
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "title": "[날씨]"
          }
        }
      ]
    }
  }
}


###

GET {{host}}/crawler-bbs-naver/_search
Content-Type: application/json
Accept: application/json

{
  "track_total_hits": true,
  "_source": [
    "title",
    "blog_name",
    "date",
    "content"
  ],
  "sort": [
    {
      "date": "desc"
    }
  ],
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "blog_name": "쿠치레 블로그"
          }
        },
        {
          "exists": {
            "field": "html_content"
          }
        }
      ]
    }
  }
}


###

GET {{host}}/crawler-bbs-naver/_search
Content-Type: application/json
Accept: application/json

{
  "track_total_hits": true,
  "_source": [
    "title",
    "blog_name",
    "date",
    "content"
  ],
  "sort": [
    {
      "date": "desc"
    }
  ],
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "cafe_name": "쿠치레레더"
          }
        },
        {
          "exists": {
            "field": "html_content"
          }
        }
      ]
    }
  }
}

###

GET {{host}}/crawler-bbs-naver/_search
Content-Type: application/json
Accept: application/json

{
  "track_total_hits": true,
  "_source": [
    "date",
    "title",
    "content",
    "reply_list"
  ],
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "cafe_name": "굿엔레더"
          }
        },
        {
          "match": {
            "title": "재봉틀"
          }
        },
        {
          "match": {
            "content": "재봉틀"
          }
        }
      ]
    }
  }
}


###


GET {{host}}/crawler-bbs-naver/_search
Content-Type: application/json
Accept: application/json

{
  "track_total_hits": true,
  "_source": [
    "date",
    "title",
    "content",
    "reply_list"
  ],
  "query": {
    "bool": {
      "should": [
        {
          "match": {
            "cafe_name": "굿엔레더"
          }
        },
        {
          "match": {
            "title": "재봉틀"
          }
        },
        {
          "match": {
            "content": "재봉틀"
          }
        },
        {
          "match": {
            "title": "미싱"
          }
        },
        {
          "match": {
            "content": "미싱"
          }
        },
        {
          "match": {
            "reply_list.text": "재봉틀"
          }
        },
        {
          "match": {
            "reply_list.text": "미싱"
          }
        }
      ]
    }
  }
}


###


GET {{host}}/crawler-bbs-naver/_search
Content-Type: application/json
Accept: application/json

{
  "track_total_hits": true,
  "_source": [
    "date",
    "title",
    "content",
    "reply_list"
  ],
  "query": {
    "bool": {
      "should": [
        {
          "match": {
            "cafe_name": "굿엔레더"
          }
        },
        {
          "match": {
            "content": "사절미싱"
          }
        },
        {
          "match": {
            "reply_list.text": "사절미싱"
          }
        }
      ]
    }
  }
}


###


GET {{host}}/crawler-bbs-naver/_search
Content-Type: application/json
Accept: application/json

{
  "track_total_hits": true,
  "_source": [
    "date",
    "title",
    "content",
    "reply_list"
  ],
  "query": {
    "bool": {
      "should": [
        {
          "match": {
            "cafe_name": "리공카"
          }
        }
      ]
    }
  }
}


###

GET {{host}}/crawler-bbs-naver/_search
Content-Type: application/json
Accept: application/json

{
  "track_total_hits": true,
  "_source": [
    "date",
    "cafe_name",
    "title"
  ],
  "query": {
    "match": {
      "cafe_name": "리공카"
    }
  }
}

###

GET {{host}}/crawler-bbs-naver/_search
Content-Type: application/json
Accept: application/json

{
  "track_total_hits": true,
  "_source": [
    "date",
    "cafe_name",
    "title"
  ],
  "query": {
    "range": {
      "date": {
        "gte": "2018-01-01",
        "lte": "2018-10-04",
        "format": "yyyy-MM-dd"
      }
    }
  }
}

###

GET {{host}}/crawler-bbs-naver/_search
Content-Type: application/json
Accept: application/json

{
  "track_total_hits": true,
  "_source": [
    "date",
    "cafe_name",
    "title"
  ],
  "query": {
    "bool": {
      "must": {
        "match": {
          "cafe_name": "리공카"
        }
      },
      "filter": {
        "range": {
          "date": {
            "gte": "2018-06-01",
            "lte": "2018-06-30",
            "format": "yyyy-MM-dd"
          }
        }
      }
    }
  }
}

###

GET {{host}}/crawler-bbs-naver/_search
Content-Type: application/json
Accept: application/json

{
  "track_total_hits": true,
  "_source": [
    "document_id"
  ],
  "query": {
    "wildcard": {
      "document_id": {
        "value": "201912*",
        "boost": 1.0,
        "rewrite": "constant_score"
      }
    }
  }
}

###

GET {{host}}/crawler-bbs-naver/_search
Content-Type: application/json
Accept: application/json

{
  "query": {
    "bool": {
      "must_not": {
        "exists": {
          "field": "articleid"
        }
      }
    }
  }
}

###

GET {{host}}/crawler-bbs-naver/_search
Content-Type: application/json
Accept: application/json

{
  "query": {
    "match": {
      "cafe_name": "고민상담카페"
    }
  }
}


###

GET {{host}}/crawler-bbs-naver/_search
Content-Type: application/json
Accept: application/json

{
  "query": {
    "bool": {
      "must": {
        "match": {
          "cafe_name": "고민상담카페"
        }
      }
    }
  }
}

###

GET {{host}}/crawler-facebook/_search
Content-Type: application/json
Accept: application/json

###

#DELETE {{host}}/crawler-bbs-naver
#Content-Type: application/json
#Accept: application/json

###

GET {{host}}/crawler-facebook/_search
Content-Type: application/json
Accept: application/json

{
  "query": {
    "bool": {
      "must": {
        "exists": {
          "field": "reply_list"
        }
      }
    }
  }
}

###

GET {{host}}/crawler-bbs-naver/_search
Content-Type: application/json
Accept: application/json

{
  "query": {
    "bool": {
      "must": {
        "match": {
          "cafe_name": "고민상담카페"
        }
      }
    }
  }
}

###

GET {{host}}/crawler-youtube-live-chat/_search
Content-Type: application/json
Accept: application/json

###

GET {{host}}/crawler-bbs-naver/_mapping
Content-Type: application/json
Accept: application/json

###

PUT {{host}}/crawler-bbs-naver
Content-Type: application/json
Accept: application/json

{
  "mappings": {
    "properties": {
      "articleid": {
        "type": "long"
      },
      "bbs_name": {
        "type": "text"
      },
      "blog_name": {
        "type": "text"
      },
      "cafe_name": {
        "type": "text"
      },
      "category": {
        "type": "text"
      },
      "clubid": {
        "type": "long"
      },
      "content": {
        "type": "text"
      },
      "curl_date": {
        "type": "date"
      },
      "date": {
        "type": "date"
      },
      "document_id": {
        "type": "text"
      },
      "html_content": {
        "type": "text"
      },
      "image": {
        "type": "text"
      },
      "nick": {
        "type": "text"
      },
      "reply_count": {
        "type": "long"
      },
      "reply_list": {
        "properties": {
          "class": {
            "type": "text"
          },
          "date": {
            "type": "date"
          },
          "image": {
            "type": "text"
          },
          "nick": {
            "type": "text"
          },
          "reply_to": {
            "type": "text"
          },
          "text": {
            "type": "text"
          }
        }
      },
      "title": {
        "type": "text"
      },
      "url": {
        "type": "text"
      },
      "view_count": {
        "type": "long"
      }
    }
  }
}

###

#PUT {{host}}/crawler-facebook/_settings

PUT {{host}}/_settings
Content-Type: application/json
Accept: application/json

{
  "index.mapping.total_fields.limit": 50000
}

###

GET {{host}}/_tasks?detailed=true&actions=*reindex
Content-Type: application/json
Accept: application/json

###

GET {{host}}/_cat/indices?v&s=index&h=index,docs.count,store.size,tm
Content-Type: application/json
Accept: application/text

###

GET {{host}}/crawler-facebook/_doc/288879321662318-479997692550479
Content-Type: application/json
Accept: application/text


###

GET {{host}}/corpus_process-naver-economy-2019/_search
Content-Type: application/json
Accept: application/json

{
  "_source": [
    "nlu_wrapper.*.moph_str"
  ]
}

###

GET {{host}}/crawler-naver-dictionary/_search
Content-Type: application/json
Accept: application/json

{
  "track_total_hits": true,
  "_source": [
  ],
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "category": "중한"
          }
        }
      ],
      "must_not": [
        {
          "exists": {
            "field": "entry"
          }
        }
      ]
    }
  }
}

###

GET {{host}}/crawler-naver-kbo_game_center_comments-2011/_search
Content-Type: application/json
Accept: application/json

{
  "track_total_hits": true,
  "_source": [
  ],
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "object_id": "20110728SSHT0"
          }
        }
      ]
    }
  }
}

###

GET {{host}}/crawler-youtube-live-chat/_doc/CkUKGkNQZmQtWXY0a2VZQ0ZhbkV3UW9kTC1ZQk5REidDUHYxME5YM2tlWUNGYlhCVEFJZDFWRU5hZzE1NzUxMTcwMDMxMzI=
Content-Type: application/json
Accept: application/json

###

POST {{host}}/crawler-bbs-lineage2m/_search?size=0
Content-Type: application/json
Accept: application/json

{
  "aggs": {
    "min_articleId": {
      "min": {
        "field": "articleId"
      }
    }
  }
}

###

GET http://172.20.92.41:9200/_cat/indices
Content-Type: application/json
Accept: application/text

###

GET http://172.20.92.41:9200/ko_tm01/_search
Content-Type: application/json
Accept: application/json

###

#POST {{host}}/crawler-dictionary-example/_delete_by_query
#Content-Type: application/json
#Accept: application/json
#
#{
#  "query": {
#    "bool": {
#      "must": {
#        "match": {
#          "entry": "cartoon"
#        }
#      }
#    }
#  }
#}

###

DELETE {{host}}/crawler-dictionary-example-list
Content-Type: application/json
Accept: application/json

###

POST {{host}}/_reindex?wait_for_completion=false
Content-Type: application/json
Accept: application/json

{
  "source": {
    "index": "crawler-dictionary-example-linedict-list"
  },
  "dest": {
    "index": "crawler-dictionary-example-linedict-enth-list"
  }
}

###

GET {{host}}/_tasks/QLnqKErAQxuOteVoPZAtBg:21000162
Content-Type: application/json
Accept: application/text

###

DELETE {{host}}/crawler-dictionary-example-linedict-enth-list
Content-Type: application/json
Accept: application/text

###

GET {{host}}/_cat/indices?s=index
Content-Type: application/json
Accept: application/text

###

#DELETE {{host}}/crawler-naver-dictionary-example
#Content-Type: application/json
#Accept: application/text

###

GET http://yonhap01:30006/_cat/indices?s=index
Content-Type: application/json
Accept: application/text


###

GET {{host}}/crawler-naver-economy-2020/_search?size=0
Content-Type: application/json
Accept: application/json

{
  "track_total_hits": true,
  "aggregations": {
    "by_day": {
      "date_histogram": {
        "field": "date",
        "keyed": false,
        "format": "yyyy-MM-dd",
        "time_zone": "+09:00",
        "calendar_interval": "day"
      }
    }
  }
}

###

GET {{host}}/crawler-naver-kbo_game_center_game_info/_search
Content-Type: application/json
Accept: application/json

{
  "track_total_hits": true,
  "query": {
    "bool": {
      "must_not": [
        {
          "match": {
            "state": "done"
          }
        }
      ]
    }
  }
}

###

GET {{host}}/crawler-dictionary-example-linedict-list/_search
Content-Type: application/json
Accept: application/json

{
  "track_total_hits": true,
  "_source": [
  ],
  "query": {
    "bool": {
      "must_not": [
        {
          "exists": {
            "field": "entry"
          }
        }
      ]
    }
  }
}

###

POST {{host}}/crawler-dictionary-example-youdao-list/_delete_by_query
Content-Type: application/json
Accept: application/json

{
  "track_total_hits": true,
  "_source": [
  ],
  "query": {
    "bool": {
      "must_not": [
        {
          "exists": {
            "field": "entry"
          }
        }
      ]
    }
  }
}

###

GET {{host}}/crawler-naver-kbo_game_center_game_info/_search
Content-Type: application/json
Accept: application/json

{
  "track_total_hits": true,
  "_source": [
  ],
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "gdate": "20200506"
          }
        }
      ]
    }
  }
}

###

GET {{host}}/crawler-naver-kbo_game_center_game_info/_search
Content-Type: application/json
Accept: application/json

{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "gameId": "20200512SKLG02020"
          }
        }
      ]
    }
  }
}

###

