### indices 목록

GET {{host}}/_cat/indices/corpus-wiki-*?v&s=index&h=index,docs.count
Authorization: Basic {{username}} {{password}}
Accept: application/text

###

GET {{host}}/_cat/indices?v&s=index
Authorization: Basic {{username}} {{password}}
Accept: application/text

###

GET {{host}}/_cat/indices?v&s=index&h=index
Authorization: Basic {{username}} {{password}}
Accept: application/text

###

GET {{host}}/_cat/indices?v&s=index&h=index,docs.count
Authorization: Basic {{username}} {{password}}
Accept: application/text

###

GET {{host}}/_cat/indices?v&s=index&h=index,docs.count,store.size,tm
Authorization: Basic {{username}} {{password}}
Accept: application/text

###

GET {{host}}/_cat/indices?v&s=index&h=index
Authorization: Basic {{username}} {{password}}
Accept: application/text

###

DELETE {{host}}/.monitoring-*
Authorization: Basic {{username}} {{password}}
Accept: application/text

###

DELETE {{host}}/.kibana_*
Authorization: Basic {{username}} {{password}}
Accept: application/text

###

GET {{host}}/_settings
Authorization: Basic {{username}} {{password}}
Content-Type: application/text
Accept: application/text

###

GET {{host}}/{{index}}/_settings
Authorization: Basic {{username}} {{password}}
Content-Type: application/text
Accept: application/text

###

PUT {{host}}/_settings
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

{
  "index": {
    "mapper": {
      "dynamic": null
    }
  }
}

###

PUT {{host}}/_settings
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

{
  "index": {
    "blocks": {
      "read_only_allow_delete": "false"
    }
  }
}

###

PUT {{host}}/crawler-bbs-lineagem/_settings
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

{
  "index": {
    "number_of_shards": 1,
    "number_of_replicas": 1
  }
}

###

DELETE {{host}}/crawler-facebook_reply
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

###

GET {{host}}/crawler-facebook-en/_mappings
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

###

POST {{host}}/_reindex?wait_for_completion=false
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

{
  "source": {
    "index": "crawler-naver-politics-2019"
  },
  "dest": {
    "index": "crawler-naver-politics-2019-tmp"
  }
}

###

DELETE {{host}}/crawler-naver-kin-rank_user_list
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/text

###

PUT {{host}}/crawler-naver-society-reply-tmp/_settings
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

{
  "index.mapping.total_fields.limit": 500000
}

###

GET {{host}}/_cat/indices?v&s=index
Authorization: Basic {{username}} {{password}}
Accept: application/text

###

GET {{host}}/_tasks?detailed=true&actions=*reindex
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

###
